### ISSUE TITLE
PREFIX: Unexpected package naming - can also be due to previously existing object

### ISSUE THREAD

**Issue by vonglan** [abapGit/abapGit#5728] opened 2022-08-22 13:02 UTC
Just for information: I noticed this error can also occur when an object was previously manually created on the target system, with a different package.
Not sure how this can be nicely documented. I suppose you have already though about a generic section "problems & solutions" section  in the documentation.
Maybe make the check more specific, and issue a more specific message.

**Comment by vonglan** [comment] 2022-08-22 13:04
(Technical reason: it_results in CHECK_PACKAGE_FOLDER (ZCL_ABAPGIT_FILE_STATUS)
contains a previously existing object with column "package" filled)

**Comment by mbtools** [comment] 2022-08-22 13:32
it should provide a better error msg. please describe a small example with package/object names so we can reproduce it

**Comment by vonglan** [comment] 2022-08-23 06:42
Originally, in our central system, I had a package ZS_DEV_TOOLS.
Then, because I wanted to use ABAPGit to transfer only parts of it into other system, I created subpackages ZS_DEV_TOOLS_COMMON, ZS_DEV_TOOLS_USAGE_AND_MONITOR and so on.
The problem was, when I tried to import package ZS_DEV_TOOLS_COMMON, some objects were already in the target system with their old package ZS_DEV_TOOLS.

Not sure whether this is relevant: I use imprt/export via ZIP, because this is much easier at my company than the "normal" way.

**Comment by mbtools** [comment] 2022-08-23 12:43
it sounds like you tried to import the subpackage `ZDS_DEV_TOOLS_COMMON` only. In that case, objects in `ZS_DEV_TOOLS` are outside of the imported repo/zip scope (`tadir` selection). Currently, abapGit is not able to change or reassign such objects to a different package. I will check how we can improve the error message if this happens.

Importing `ZDS_DEV_TOOLS` (with all its subpackages) should work because then the already existing objects are part of the repo/zip and can be reassigned by abapGit.

**Comment by vonglan** [comment] 2022-08-24 12:26
That is also how I see it. 
I did not want to import the complete "super" package.
These packages contain tools/objects that were not originally designed to be implemented in other systems.

Thanks for your work on this great tool!

**Comment by mbtools** [comment] 2022-09-07 00:29
I added a chapter to the docs. https://github.com/abapGit/docs.abapgit.org/pull/45

**Comment by vonglan** [comment] 2022-09-08 06:44
The updated documentation looks excellent!
But I did not find the exact case from this ssue.
Or did you also adapt the codng to give a better error message for this case?

**Comment by mbtools** [comment] 2022-09-08 18:55
I tried a few times to reproduce it but always got `Package and path do not match for object` instead of the `PREFIX ....` error you got. 

You wrote the issue was because of objects in a different/wrong package but the error is related to packages that don't fit the package hierarchy of your repo. Did your export package match the import package? Did you have sub-packages in the ZIP?

A test repo would be the best. If not maybe a screenshot of the folder/files tree.

**Comment by vonglan** [comment] 2022-09-15 07:49
I tried to reproduce it.
My package hierarchy is
Z_DRAEGER
-- ZS_BASIS
---- ZS_DEV_TOOLS
------ ZS_DEV_TOOLS_COMMON
I changed the package assignment for one object from ZS_DEV_TOOLS_COMMON to ZS_DEV_TOOLS.
Then I tried to Import ZIP for ZS_DEV_TOOLS_COMMON (which has just that package, no subpackage).

At first I got the "PREFIX" message only on a 7.40 system. Later (after downloading the current abapgit_standalone - maybe that made a difference) I could also reproduce it on a 7.56 system.

The reason is that ZS_DEV_TOOLS is under a package ZS_BASIS!
It happens with this callstack:
26		METHOD	PACKAGE_TO_PATH	ZABAPGIT_STANDALONE		ZABAPGIT_STANDALONE	102.392
25		METHOD	CHECK_PACKAGE_FOLDER	ZABAPGIT_STANDALONE		ZABAPGIT_STANDALONE	102.891
24		METHOD	RUN_CHECKS	ZABAPGIT_STANDALONE		ZABAPGIT_STANDALONE	103.162
23		METHOD	STATUS	ZABAPGIT_STANDALONE		ZABAPGIT_STANDALONE	103.212
22		METHOD	STATUS	ZABAPGIT_STANDALONE		ZABAPGIT_STANDALONE	55.310
21		METHOD	BUILD_REPO_ITEMS_WITH_REMOTE	ZABAPGIT_STANDALONE		ZABAPGIT_STANDALONE	54.358
20		METHOD	LIST	ZABAPGIT_STANDALONE		ZABAPGIT_STANDALONE	54.490
(ABAPgit freshly downloaded this morning, merge marker 2022-09-13T14:40:27.777Z)

check_package_folder is called with iv_top = ZS_DEV_TOOLS_COMMON
and it_results has one entry with package = ZS_DEV_TOOLS, all the others are ZS_DEV_TOOLS_COMMON

When I switch Folder Logic from PREFIX to FULL, as suggested, system says: 
Package and path do not match for object DTEL ZS_LAST_LINE.

So everything seems fine now. 
One improvement would be if the prefix message would also state the clashing package names (in my case ZS_BASIS vs. ZS_DEV_TOOLS).

Ah! The [documentation](https://docs.abapgit.org/ref-folders-filenames.html) says the full message is:
`Unexpected package naming ({ package }). You might switch the folder logic Folder logic: length = 0, parent: { parent_package }, child: { package }`
However, I only get displayed
` PREFIX: Unexpected package naming (ZS_DEV_TOOLS)you might switch the folder logic`

**Comment by mbtools** [comment] 2022-09-20 22:14
I was now able to reproduce it with online as well as offline repos. Working on a fix

**Comment by mbtools** [comment] 2022-10-04 20:39
Reproducible test case:
https://github.com/mbtools/ZS_DEV_TOOLS_COMMON

1. Create two packages

![image](https://user-images.githubusercontent.com/59966492/193921698-a5752e88-391c-4c43-ad7d-8ad9ba40f5f7.png)

2. Create repo for package ZS_DEV_TOOLS_COMMON
3. Pull repo 

![image](https://user-images.githubusercontent.com/59966492/193921852-1376f75b-cc1a-45eb-b98c-60b1046440f3.png)

![image](https://user-images.githubusercontent.com/59966492/193922249-25fc6688-c0b3-4522-97e8-09120e07fc48.png)

4. Assign data element ZS_LAST_LINE to package ZS_DEV_TOOLS

![image](https://user-images.githubusercontent.com/59966492/193921311-9b35618b-a7fa-4c8e-8ad6-f0fe68460c10.png)

5. Refresh repo

Before fix:

![image](https://user-images.githubusercontent.com/59966492/193922349-c2c14cfb-9b9b-4b42-ad89-6e253d41099a.png)

After fix:

![image](https://user-images.githubusercontent.com/59966492/193922366-daeb242d-fe0d-419e-8d6f-526f2e432f04.png)

Fix https://github.com/abapGit/abapGit/pull/5805

**Comment by mbtools** [comment] 2022-10-07 12:56
Please test

**Comment by vonglan** [comment] 2022-10-25 13:10
Hi, thanks for fixing this.
Is the test still to be done? 
If yes, how can I get the "testworthy" standalone version of the report? (I have no online github connection)

**Comment by mbtools** [comment] 2022-10-25 17:53
Yes, some testing is appreciated. Standalone version which includes the change is attached here:

[zabapgit_standalone_5805.zip](https://github.com/abapGit/abapGit/files/9862708/zabapgit_standalone_5805.zip)

**Comment by vonglan** [comment] 2022-11-01 14:56
Hi,
I finally tested, sorry for the delays.
In my test, I had some more objects with wrong packages:
![image](https://user-images.githubusercontent.com/17814756/199262539-792380ef-91bd-4f05-b971-b7ec550f5f74.png)

The new popup showed up correctly:
![image](https://user-images.githubusercontent.com/17814756/199262729-3c403771-cd3d-4c94-be1d-c58ea370f005.png)

Complications (because of my testcase):
- some changes were modifications (this is a sandbox, and it seems I did not reset all TADIR-SRCSYSTEM)
- one Syntax error due to missing dependent DTEL, which I overcame with "activate anyway"

Result messages:
![image](https://user-images.githubusercontent.com/17814756/199262858-37cabb7b-341c-4bdc-bc5d-baa65776cd2d.png)

The first two lines are syntax warnings (not to do with ABAPgit)

Not sure where the other two lines come from.
The function group is one that had "wrong" package assignment in my test case
When I check the function group consistency with SE37 / Tools / Repair function group, no problems are found.

ZS_LAST_LINE is correctly in the other package.

Should I delete the function group and pull again?

Best regards,
Edo

**Comment by vonglan** [comment] 2022-11-02 07:30
Thanks for the bugfix (or improvement)!

**Comment by vonglan** [comment] 2022-11-02 07:51
I just retested this, to be sure about the "Error updating where-used list" error.
I got it again.
I will debug.

**Comment by vonglan** [comment] 2022-11-02 08:30
The reason for "Error updating where-used list" is that when SAP standard is called to update the where-used list, it encounters the syntax error (which I ignored with "acticate anyway").
It might be helpful to add
- the object name to that message 
- and the hint "(possible reason: ignored syntax errors)"

**Comment by mbtools** [comment] 2022-11-02 13:25
I updated the error message in #5849 

Please leave a short msg in https://github.com/abapGit/abapGit/pull/5805 that it was tested successfully. Thx

**Closed** 2022-11-04 12:56 UTC
