### ISSUE TITLE
Error <object> already exists outside of <...> package hierarchy due to missing packages

### ISSUE THREAD

**Issue by pokrakam** [abapGit/abapGit#6784] opened 2024-01-30 16:18 UTC
This is more to document an issue I encountered following an S/4 upgrade. Perhaps the error handling could be improved, but not the highest priority.

When I wanted to update abapGit, it came back with a bunch of these:
<img width="806" alt="image" src="https://github.com/abapGit/abapGit/assets/25539927/e9e3507a-deda-4194-aeba-31586b7a167d">

It turns out that the upgrade (S/4 2022 -> 2023) wiped out all non-SAP local packages starting with `$`. Just deleted, leaving orphaned objects, and everything still functioning as normal. 
The message was misleading, could possibly be improved here: https://github.com/abapGit/abapGit/blob/01df9ce9484ca261fbbdc83a98b90730d4345264/src/repo/zcl_abapgit_repo_status.clas.locals_imp.abap#L222 but definitely not a high priority. My first thought is to simply check if the assigned package actually exists and just pull the package if not. That's working around a situation that isn't consistent to start with.

My solution was to run abapGit standalone, then on the pull screen only selecte `DEVC`'s to pull all the packages first and get the system consistent before pulling anything else, just to be on the safe side.
![image](https://github.com/abapGit/abapGit/assets/25539927/48fd3b27-8393-4688-9c23-93793d3b72c9)
(as an aside, the background of this popup reloads unnecessarily after each tick mark, causing a delay of several seconds per click)

There were a few more 'odd' messages on subsequent pulls (duplicate instances of objects found and others), but after 3-4 pulls it eventually corrected itself and got back to a clean pull state.

**Comment by larshp** [comment] 2024-01-30 16:20
also see #3224

**Comment by mbtools** [comment] 2024-01-30 17:08
i hate changing custom code to work around SAP bugs. how on earth did the upgrade drop $ packages? what's the SAP note/fix for this?

**Comment by pokrakam** [comment] 2024-01-30 18:11
Oh don't get me started talking to SAP about it... we're on RISE, which in marketese means SAP manage the system and it's all wonderfully cloudy and fluffy and they're with you every step of the way. The reality is that SAP outsource their part and we have to deal with a shocking level of incompetence (*). So I don't bother asking because life's too short.

But interesting that other have experienced this on a 1709->1909 upgrade, so this is a regular thing. I also have my own local $ZPACKAGE and sub packages underneath that and they also all got wiped out. The object still exists and references `$Z...` in TADIR but the package itself is gone. 

(*): For example, it took two months just to get connectivity from Private Cloud to GitHub. Should in theory be a simple matter of adding GitHub.com to a firewall allowlist or similar. Several tickets, several attempts to explain the requirement. Then they kept assuring us it was done and each time we gave them the same SM59-test-failed screenshot and instructions how to use SM59 to test it.

**Comment by pokrakam** [comment] 2024-01-30 18:22
And the background update is not related to the SAP Note or issue. It's this: 

https://github.com/abapGit/abapGit/assets/25539927/4c25bf4b-ec48-406a-8370-edd28b0d7f58

With more objects the refresh takes longer, 4-5 seconds on my case. Not a big deal, and may be related to my using HTMLGUI.

**Comment by mbtools** [comment] 2024-01-30 19:29
That's unfortunately a general issue with HTMLGUI: round trips refresh all of the HTML

**Comment by mbtools** [comment] 2024-01-30 19:56
Possible root causes for the missing $ packages:

- SAP Note [2478895](https://me.sap.com/notes/2478895) - ATO Package Lost in Upgrade
- SAP Note [3066003](https://me.sap.com/notes/3066003) - Check of changeability of $ package component

In transaction S_ATO_SETUP, you can find a little hint:

"Please use packages which will survive the upgrade (e.g. packages which start with "TEST" )."

![image](https://github.com/abapGit/abapGit/assets/59966492/0d8c181b-bcd2-4ed3-8810-00e5569d6f3e)

**Comment by pokrakam** [comment] 2024-01-30 21:01
Hey Marc, great find!
The first note does state it explicitly:

_In an upgrade all $ Packages get lost 
Solution
1 Solution: Recreate the $ packages_

So I guess it wasn't just a quirk of our upgrade but a general 'feature' of upgrades. Thanks for confirming. 

Let's leave this issue open for a couple of weeks and I'll see if I can find time to fix up as this may be worth addressing if it's going to affect anyone who's using a $ package and upgrading.

**Comment by christianguenter2** [comment] 2024-01-31 16:58
Yeah, I'm dealing with wiped out $-packages every other week. So certainly a fix for this would be appreciated.
Also had some upgrades where basis consultants insisted on deleting all $-packages before the upgrade.

**Comment by larshp** [comment] 2024-01-31 17:45
![image](https://github.com/abapGit/abapGit/assets/5888506/021f55e9-7a29-4a2e-a686-f0578d7bae8e)

**Comment by mbtools** [comment] 2024-01-31 19:37
Modern day practice:

Serialize TDEVC and TDEVCT to a repo before SAP upgrades 😉

**Comment by larshp** [comment] 2024-02-01 06:55
> Modern day practice:
> 
> Serialize TDEVC and TDEVCT to a repo before SAP upgrades 😉

or just move the code thats needed in DEV to production

anyhow, theres also packages starting with something like "TEST_" or something, which acts like "$", perhaps they are handled differently?

**Comment by mbtools** [comment] 2024-02-01 07:51
apparently T-packages survive. still i call this a major sap bug. as a customer i would not rest until i had an SAP note

**Comment by larshp** [comment] 2024-03-30 09:10
close? the packages were deleted by SAP

**Comment by pokrakam** [comment] 2024-04-01 20:35
Given this is a known 'quirk', I still think abapGit's handling should be improved. When I last looked at it, it was not a 5 minute fix, but I may have some time over the next week or two.

The message is correct if the object belongs to another package. But for the scenario where it belongs to a nonexistent package we can do two things: 
1. Provide a different message
2. Pull the package if it does fit into the hierarchy

I'll do 1. as I think this is the minimum we should do. 
2 is a nice to have, but was a bit fiddly when I looked at it as the code was already modified to work in the other direction. Will poke around a bit more but I don'1 think it's high priority so if it gets messy we can leave it.

**Comment by mbtools** [comment] 2024-04-02 07:27
Agree. If an object is orphaned (tadir entry with package that does not exist), then it should issue a warning (instead of the error) and restore the package on pull.

**Comment by mbtools** [comment] 2024-04-08 16:01
Here's a small test case:
https://github.com/abapGit-tests/PROG, branch "subpackage"

Pull everything to package `$PROG`, then delete the `TDEVC` and `TDEVCT` entries for the packages `$PROG` and `$PROG_SUB` (simulating the upgrade issue).

The problem is not the status calculation. It's the selection of local objects (`zcl_abapgit_tadir=>select_objects`). AG first selected all packages and sub-packages. This is where the missing `TDEVC` entries "hurt": No sub-packages are found. The root package of the repo is added by default.

The subsequent object selection is based on the found packages and therefore won't find any objects for the sub-packages. In turn, the objects are not serialized and the status calc will treat them as non-existing locally. 

Without the package hierarchy (in `TDEVC`), there's no way for AG to determine which objects belong(ed) to a repo. 

PS: The root cause is SAP dropping packages. I firmly believe SAP should fix this (or provide an easy way for customers to restore the local packages + package hierarchy after the upgrade).

**Comment by mbtools** [comment] 2024-04-24 14:57
Close?

**Comment by pokrakam** [comment] 2024-04-24 18:15
Yeah, thanks

**Closed** 2024-04-24 18:15 UTC
Labels: discussion, sapfix
