### ISSUE TITLE
Opening compare editor has encountered a problem

### ISSUE THREAD

**Issue by mrsetosan** [abapGit/abapGit#5443] opened 2022-04-04 12:17 UTC
Hi there,

by trying to call the functionality of the compare editor Eclipse returns an error:
![grafik](https://user-images.githubusercontent.com/25388472/161541358-15af077d-b6c9-48c9-897f-756d9f5aafa5.png)
![grafik](https://user-images.githubusercontent.com/25388472/161541337-2009dd51-1af1-41b8-99f0-19231e93ba7a.png)

Unfortunately I don't know how to handle the error message because the credentials to the remote repository are configured correctly.
Pushes and fetches work fine.

So I would like to know if anyone can tell me if this feature is even implemented in abapgit yet and maybe how to resolve the issue.

Remark: I use an online remote repository, no offline!

BR

**Comment by larshp** [comment] 2022-04-04 12:28
@mrsetosan is this on a Steampunk system?

**Comment by mbtools** [comment] 2022-04-05 08:33
Probably duplicate of https://github.com/abapGit/abapGit/issues/5189

**Comment by mrsetosan** [comment] 2022-04-07 10:41
> @mrsetosan is this on a Steampunk system?
Haha no. It's Eclipse in dark mode.

> Probably duplicate of #5189
Exactly. It matches #5189 and [ADT Backend Issue #71](https://github.com/abapGit/ADT_Backend/issues/71).
I think this is a dependency to the ADT Backend issue and therefore it won't be able to be fixed before?

BR

**Comment by mbtools** [comment] 2022-04-07 13:33
Can you test https://github.com/abapGit/abapGit/pull/5458, please?

**Comment by mbtools** [comment] 2022-04-08 15:02
#5458 has been merged. should fix this.

**Closed** 2022-04-22 11:39 UTC
