### ISSUE TITLE
Focus html control on abapgit startup

### ISSUE THREAD

**Issue by FreHu** [abapGit/abapGit#4816] opened 2021-06-01 16:23 UTC
When abapgit starts, the focus is here:
![image](https://user-images.githubusercontent.com/5097067/120357981-4e8cc300-c306-11eb-820c-954017ecd923.png)

I'd like to focus the html control on startup/page load so that you can press keyboard shortcuts immediately, is it possible?

**Comment by mbtools** [comment] 2021-06-01 16:40
+1 
I'm not sure. The problem is that there are no fields on the dynpro 1001. Therefore, it defaults to the command field. 
https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-us/abapset_cursor_dynpro.htm

**Comment by FreHu** [comment] 2021-06-01 18:01
I found the methods
```
cl_gui_control=>set_focus( ).
cl_gui_control=>get_focus( ).
```
but they don't seem to work here. I tried to focus the html viewer as well as the screen0 container, but nothing happens. 
Calling get_focus immediately after set_focus will dump on a `cntl_error`

**Comment by mbtools** [comment] 2021-06-01 18:05
Correct. I got it to work and will put it in a PR for testing.

**Comment by mbtools** [comment] 2021-06-01 18:13
Try #4817. Needs some testing with Web GUI, Java GUI so we don't crash those.

**Comment by FreHu** [comment] 2021-06-01 18:52
In windows sapgui it works. I noticed that on pages where there is a filter (repo list/stage), it is now focused automatically

**Comment by mbtools** [comment] 2021-06-01 19:23
doesn't focus with forms like settings but I think that's an HTML thing.

**Comment by FreHu** [comment] 2021-06-01 19:33
if the browser has focus now we should be able to focus the right element in javascript on load

**Comment by mbtools** [comment] 2021-06-02 10:22
no js necessary. what's missing is the `autofocus` attribute for the first form field. we can add this in `zcl_abapgit_html_form` after #4771 is merged

**Closed** 2021-07-06 09:41 UTC
Labels: question
