### ISSUE TITLE
SFBF: Deserialization fails

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abapGit#2469] opened 2019-02-28 14:30 UTC
Demo repo
https://github.com/abapGit-tests/SFBF.git

Diff after pull
![image](https://user-images.githubusercontent.com/17437789/53573186-30efb280-3b6d-11e9-8ed6-9dd2249c99a8.png)

And a shortdump when navigating to the object via abapGit or tx SFW2 
![image](https://user-images.githubusercontent.com/17437789/53573208-3e0ca180-3b6d-11e9-8ceb-6386bd570022.png)

![image](https://user-images.githubusercontent.com/17437789/53573293-6f856d00-3b6d-11e9-991b-1173fbb0cf94.png)

![image](https://user-images.githubusercontent.com/17437789/53573298-72805d80-3b6d-11e9-9a71-0efb863d6c65.png)

**Comment by larshp** [comment] 2019-02-28 14:31
is this a new bug or has it been broken for a long time?

**Comment by christianguenter2** [comment] 2019-02-28 15:20
Seems quite new.
abapGit CI says that it was ok on february 20th
https://github.com/abapGit/ci.abapgit.org/blob/b59a93e8cf88410d7ae85d4d7ed98b7555cd1a8a/src/08002743b1381ed8b8a29429c189dd50.smim.abapgit_ci_result.html#L813-L825

and failed the first time on february 21th
https://github.com/abapGit/ci.abapgit.org/blob/dc1b558cb0079b94c57fae6f46b1af0cd9169a35/src/08002743b1381ed8b8a29429c189dd50.smim.abapgit_ci_result.html#L813-L825

Wasn't that the time we merged parallel DDIC activation? But could also be a coincidence.

**Comment by larshp** [comment] 2019-02-28 15:37
yea, guess the problem is the parallel ddic activation, I'm also not sure if I would categorize SFBF as DDIC

**Comment by GoWale** [comment] 2019-03-19 20:23
yes side effects of the new DDIC actiavtion.
Fixed in the draft #2518 seems it needs the old activation function.
I think this is for SFBF, SFBS and maybe SFWF?

**Comment by christianguenter2** [comment] 2022-01-04 08:22
Meanwhile the object is deserialized but inactive.
![grafik](https://user-images.githubusercontent.com/17437789/148029986-7c5eb892-653a-46fb-b94a-70e3181c9d1b.png)
![grafik](https://user-images.githubusercontent.com/17437789/148029992-f569aa4a-7c5a-4f91-a550-7c56c10c0543.png)

**Closed** 2023-02-01 09:29 UTC
Labels: serialization, bug, ci
