### ISSUE TITLE
Pull only selected files?

### ISSUE THREAD

**Issue by nununo** [abapGit/abapGit#413] opened 2016-11-09 12:13 UTC
Hello,

Currently when I press PULL... all objects with differences are automatically overwritten.

Due to some issues probably related to SAP versions, when I stage my changes from source system A into target system B... even though all the code is properly sync'd, I still get eternal diffs, most times small irrelevant flags which I don't know how to change.

For example, most times the TOP include of a function group insists in showing this diff in the target system B:

Local: `<VARCL>X</VARCL>`
Remote: `<VARCL/>`

Sometimes a repository has several files which are ok but still show diffs. As a result, whenever I pull a repository in the target system... instead of just updating that small tweak... it unnecessarily rewrites function groups, classes, tables, etc.

Also, sometimes I have committed multiple changes in source system and in the target system just want to pull a specific one.

Given this, would it be feasible to implement a way to selectively pull only selected objects?

Thanks,
Nuno

**Comment by larshp** [comment] 2016-11-11 08:38
small diffs: I have been thinking perhaps we should build a feature so it does not display these as diffs, but not sure how

TOP includes: I think there is an open issue on this

pull only selected files: would this be due to performance? how many objects do you have in the repository?

**Comment by nununo** [comment] 2016-11-11 09:00
> small diffs: I have been thinking perhaps we should build a feature so it does not display these as diffs, but not sure how

I also wondered if there was a simple way to deal with this. But still didn't figured it out.

> pull only selected files: would this be due to performance? how many objects do you have in the repository?

No, not performance, no:
- Mostly due to all these small diffs that I can't get rid of and which make it look like things are not properly sync'd;

- And also because I thought that it could be useful to have a more granular control over pull, in case I really want to surgically update just a single file if I know that a full pull will screw up other stuff around still expecting previous versions of the repository being sync'd;

- And because sometimes I still get syntax errors when pulling several things at the same time. I still didn't report issues on this because I want to better understand the reasons behind it happening. And I'll keep having to deal with those syntax errors every time I pull a repository which has objects with eternal diffs due to those small flags.

**Comment by larshp** [comment] 2016-11-11 09:16
cool, why not :smile: 

I think the feature should be added under the "Advanced" menu, to keep the normal workflow as simple as possible, and still enable it for power users

**Comment by nununo** [comment] 2016-11-11 09:18
:)

I fully agree that we shouldn't mess with the simplicity of the existing process. The "Advanced" menu is where I'd put it also ;)

**Comment by sbcgua** [comment] 2016-11-11 10:31
An opinion

This idea seems to contradict the GIT idea in essence. Let's say you applied some partial pull. What kind of state is that ? Which branch/commit hash ? Or e.g. you pull file A (partial), let's say commit hash is not changed so this is treated as "local change", then A changed remotely and B locally and you want to commit B - but abapGit will want to commit both A (an older one than remote!) and B ! Mmmm, really confusing imho.

On the other hand it could be very nice to ignore diffs caused by system differences. Like that <VARCL>. Or e.g. sync between 730 and 740 ! 740 has a number of new fields - and there are always diffs :( Maybe set of fields in XML should be restricted ... but again - what if repo if synced between 740 and 740 and they are meaningful ... the solution is unobvious for me :( (How does SAP manages that in their transports ???)

**Comment by larshp** [comment] 2016-11-11 12:23
I guess(as always) it would be pretty easy to implement :smile: In @nununo's scenario I think he never pushes from this system, so he'd not need to consider the state. I agree it contradicts some of the Git idea, but I also see that this is something that could be nice to have

**Comment by sbcgua** [comment] 2016-11-11 13:15
> I guess(as always) it would be pretty easy to implement 

If you mean basis version then oh yes ... we had similar issue with our internal deployment tool. Not solved by now ... :) (maybe in abapGit will be faster hehe =)

**Comment by nununo** [comment] 2016-11-13 18:49
It was just a suggestion... I wouldn't want to screw up abapGit's adherence to git's concepts. Still, if the pull of a specific object A just overwrites the local object with its repository version,... it could leave everything in the same state, just as if the changes in object A had been manually done.

Still, it would stop showing as a diff line since it is now similar to the repository.

I am not familiar with the low level way abapGit is implemented so maybe what I say is lame and doesn't make sense. If that's the case, sorry!

**Comment by sbcgua** [comment] 2016-11-14 17:51
No sorrys, any idea is good to check :)
I even mentioned a "pull control" page in UI wishlist #346 although I meant a bit different functionality.
Maybe you are right and just leaving the partial pull like local changes should work fine.

**Comment by EduardoCopat** [comment] 2017-10-06 18:34
Hm, does #934 fixes this?

**Comment by larshp** [comment] 2017-10-07 04:12
hmm, 934 is kind of in the same direction

but what if I did not modify the file locally, and do not want the remote version, but only want the remote version for some of the files?

**Comment by sujaymeshram** [comment] 2020-07-31 21:42
This is very important feature to have in abapGit. Let me explain the current scenario in our current org, where it can be very helpful -

We have packages for each business process for ex. YSP for Sales Planning, YFI for Finance etc. with no sub-packages at all. Each of it contains more 400+ artifacts. It's really hard to convince the MANAGEMENT to change the package structure now!!! We use the same project landscape for all the releases. At a given point in time, we might be developing for various releases on the same system. We also have a BugFix landscape. When a release goes live we shut the BugFix landscape for a week for the sync activities with the latest release and meanwhile any production bugfix is done via Project landscape.

Now imagine, Class A was modified in Release1 and Release 2(new method was added). Release 1 was moved to prod, but we immediately got a prod bug. Now, we have to revert the changes done in Release 2 and bring back the code to the Release 1 version. Make the fix and then send it to Production and again add the Release 2 changes back to Class A.

If we try to use abapGit in our case, when I try to pull the Release 1 version from Git Branch, it changes all the common artifacts modified in both the releases, because of the single large Package. The selective pull will allow me to only get Class A changes for Release 1 from the Package!

I am willing to help here and make the code change, just require some advice for the best way of achieving it.  Also, I am new to this open-source contribution stuff...would require some help with that too...

I intend to add a hyperlink to pull each artifact from the repo, as shown in the below image.
![image](https://user-images.githubusercontent.com/26520125/89079596-7472cf80-d3a4-11ea-86e8-82cdcfbf8c23.png)

**Comment by yellappam** [comment] 2021-02-09 10:18
Recently, we have started using abapGit as part of S/4HANA implementation. For some packages, the PULL functionality didn't work completely and even some simple objects, ex: reports, are not pulled due to inter dependencies. I have pulled tables first then views and then function group and then reports. To achieve this, temporarily I have filtered LT_RESULTS internal table in zcl_abapgit_objects=>deserialize in debug mode and finally it worked for some scenarios. I think, implementing the "pull only selected files" functionality would be useful for such scenarios.

![image](https://user-images.githubusercontent.com/29766214/107348897-79bb8e80-6b2c-11eb-9d88-ea266a7183ad.png)

**Comment by JanisB-AT** [comment] 2021-02-09 11:48
I can confirm that a complete "Pull" (reinstall) of not too complex but quite big repo of _transportable_ objects previously backed up and uninstalled completely using AbapGit did not work 100% cleanly. If I remember correctly, in my case the issues were mainly related to uninstalled "SM30 dialogs" and the related DDIC. By "uninstalled completely" I mean - inclusive of release of deletion transport , so that TADIRs are cleaned out from the (original development) system.

I have unsuccessfully tried to quickly "hack on" a "selective pull" - using developments from 934 and  generally the existing "overwrite checks" infrastructure. Somewhat infuriatingly and tantalizingly, if the TADIRs of uninstalled objects are still in the system, functioning "selective pull" is kind of already there, - as a side effect of current "overwrite checks" logic... 

My idea was: hack in another popup showing all objects with the diffs, in order to then pass the object selection as "overwrite checks" result. The biggest obstacle for my main envisioned use case -- selectively restoring from an online backup repo of decommissioned packages -- was exactly the checks_adjust( ) above. It reprocesses the checks passed in, discarding the "irrelevant  checks", and leading to unconditional pull of all objects in state "XA" (remote objects not existing locally).  

Then I tried to hack in "selective pull" by spoofing non-existing TADIRs of the objects to be restored via TADIR read user exit... Also did not succeed (stuff is programmed "properly defensively" there :D), and did not want to compromise by letting the TADIRs to be persisted before the objects themselves have been successfully pulled. 

Which is why I liked and still like #4282 - because it would address the resulting "popup overload". Proper "selective pull" page would be preferable, but all the HTML/javascript stuff is beyond my competence, so I might yet implement https://github.com/abapGit/abapGit/issues/4282#issue-756391593 in a fork...

**Comment by larshp** [comment] 2021-02-09 12:42
Well, I suggest starting out by helping out with some of the smaller tasks, write some unit tests, do some testing on smaller examples etc. This will hopefully free up some time for the people with more years in the codebase to start helping with this task.

**Comment by sbcgua** [comment] 2021-02-18 19:36
ref #3705, constantly fighting with some selective-pull-related issues.

I think, in terms of code, there should be some construct, let's call it "schedule", which defines in which order and which objects are pulled. Such a construct will allow playing more easily with pull sequences, maybe even manually defined (e.g. pull ddic, then pull IFs from subpackage X, then IFs from package Y, then everything else). Maybe the pull sequence can also be autoprebuild by abaplint or whatever ... because at the end of the day it is a tree of dependencies. And of course the "schedule" can be filled completely manually - which is from a popup. The "schedule" is then a parameter to deserialize process.

**Comment by larshp** [comment] 2021-02-19 04:12
schedule: it exists and refactor task = https://github.com/abapGit/abapGit/issues/3536

would a schedule replace a selective pull feature? if not its out of scope for this issue

**Comment by sbcgua** [comment] 2021-02-19 20:42
Imho, "schedule" is a primitive behind to ensure automatic or manual (this issue) deserialization order. Anyway needs some coding experiments.

**Closed** 2021-05-20 04:19 UTC
Labels: new feature
