### ISSUE TITLE
Table and View: Old field removal and new field additional - Error during PULL

### ISSUE THREAD

**Issue by yellappam** [abapGit/abapGit#4496] opened 2021-02-07 22:38 UTC
Hi,

I am using abapGit version: 1.104.0 and ABAP Version: 750. There is an error during the PULL which can't activate table and view due to interdependency( old field removal and new field addition). Below are the steps to replicate the issue.

1. Create a new table and database view. View includes all the fields from table. ( System1 )
2. PULL this into another system. This steps works without any issue( System2 )
3.  Remove old field and add new field to both table and view. ( System1 )
4. PULL this into second system. ( System 2)

In the 4th step, getting errors which need to be fixed manually. I was expecting this to be automatically fixed during PULL. I have attached the document with steps along with manual steps to fix the errors. Please suggest if this is a bug or manual steps are expected.

[Issue replication steps.docx](https://github.com/abapGit/abapGit/files/5940189/Issue.replication.steps.docx)

Regards,
Yellappa.

**Comment by larshp** [comment] 2021-02-09 09:47
yea, hmm, not sure what to do about it

**Comment by JanisB-AT** [comment] 2021-02-09 13:03
DDMODE = 'T' (Transport instead of Original System) via Debugger in here looks promising on 7.40 SP 23. 
![image](https://user-images.githubusercontent.com/9512588/107366945-02134280-6adf-11eb-8a03-99a358f5f2e0.png)

I have to repeat the procedure on a "clean system" to be sure, but with the 'T' I only got view activation error, and in the end main branch was cleanly in the system.

**Comment by mbtools** [comment] 2021-02-09 14:23
Could you please try to reproduce this with one system and a public repo with two branches? 

1. Create branch1
1. Create a new table and database view. View includes all the fields from table. Commit to branch1
1. Create branch2
1. Remove old field and add new field to both table and view. Commit to branch2
2. Switch to branch1 and pull (should result in original table/view without errors)
3. Switch to branch2 and pull (should result in changed table/view without errors)

**Comment by JanisB-AT** [comment] 2021-02-09 20:49
@mbtools - failed at 5. 
![image](https://user-images.githubusercontent.com/9512588/107425736-a321ed80-6b1f-11eb-8fe5-bace79517ff1.png)
This [change](https://github.com/abapGit/abapGit/compare/master...JanisB-AT:master?diff=split#diff-d8063418e42d6d11afd3a346d329a01055ed67dc6b57fdaefdc7037a30052ec7), which, according to log contents, mimics CTS DDIC activation job behavior in the target system (7.40 SP 23), seems to work.

**Comment by larshp** [comment] 2021-02-10 16:28
@JanisB-AT can you help opening the change as a pull request? that makes it easier for people to test it

**Comment by JanisB-AT** [comment] 2021-02-10 18:20
Unfortunately, it's next to impossible to discern whether the behavior/parametrization of CTS job might have changed since 7.4 SP 23 just by looking at OSS Notes - the underlying code is "difficult"...

**Comment by JanisB-AT** [comment] 2021-02-10 18:40
No, still not good - something is not right with the DB Object, event while it shows DDIC as active...

**Comment by mbtools** [comment] 2021-02-10 19:08
I'm able to reproduce it on my 750 system with your repo ttps://github.com/JanisB-AT/Test_4496

I will take a closer look.

**Comment by mbtools** [comment] 2021-02-10 21:45
Some background: Using prg RADPROTA, you can see the complete activation log (log name = ABAPGIT*). The log shows that the system tries to activate the table before the view. This is not possible since at that time the view has not changed. 

A possible solution is to force the DDIC activation. `ZCL_ABAPGIT_OBJECTS_ACTIVATION=>ACTIVATE_DDIC`:

```abap
      CALL FUNCTION 'DD_MASS_ACT_C3'
        EXPORTING
          ddmode         = 'O'
          medium         = 'T' " transport order
          device         = 'T' " saves to table DDRPH?
          version        = 'M' " activate newest
          frcact         = abap_true  "<<<< Force activation
          logname        = lv_logname
          write_log      = abap_true
```

With this change, it's possible to switch between branch1 and branch2 and pull each without errors. 

I'm not sure if this change should become part of AG or should be switchable... @larshp?

**Comment by larshp** [comment] 2021-02-11 05:41
Currently, classes are forcefully activated, so I guess we can do the same with DDIC.

Just need to work on better showing errors after import, would like to run the syntax check and if there are errors show it to the developer.

When doing import, I assume the goal of the developer to activate the objects, so abapGit might as well help as much as possible

**Comment by JanisB-AT** [comment] 2021-02-11 08:31
@mbtools: I can't force the thing to activate using 'check mode' (DDMODE) 'O', no matter what I do with 'frcact', 'delall' and 'inactive' in 7.40 sp 23... 
![image](https://user-images.githubusercontent.com/9512588/107614660-0e1c1300-6c4b-11eb-83cb-2bd80acfebf3.png)

[ABAPGIT_20210211_085425.txt](https://github.com/abapGit/abapGit/files/5963815/ABAPGIT_20210211_085425.txt)

Could you please try, with frcact = abap_true:
1. Uninstall and reclone https://github.com/JanisB-AT/Test_4496
2. Pull master (should be Ok, just package is there)
3. Switch to and pull branch1 (should be ok) 
4. Switch to and pull branch2 (fails on 7.40 sp 23 with the attached log)

**Comment by mbtools** [comment] 2021-02-11 14:17
7.50 SP 19: Works flawlessly

![261](https://user-images.githubusercontent.com/59966492/107646558-17f04700-6c48-11eb-8621-81916e93826b.gif)

[ABAPGIT_20210211_140304.txt](https://github.com/abapGit/abapGit/files/5966007/ABAPGIT_20210211_140304.txt)

Only change was adding `frcact = abap_true`. 

Your log is with the "inactive" and "delete all". Revert to what it was and just add "force".

**Comment by JanisB-AT** [comment] 2021-02-11 15:45
Wierd stuff... :)
![2021-02-11_16h11_47](https://user-images.githubusercontent.com/9512588/107657828-d3839c00-6c85-11eb-8217-c76ef17c877c.gif)

[ABAPGIT_20210211_161058.txt](https://github.com/abapGit/abapGit/files/5966527/ABAPGIT_20210211_161058.txt)
Do you notice any obvious differences compared to your 7.50 log?

I'll experiment a bit with the 'G' mode (relaxed checks or something like that). There are, when one looks deep enough in the code, also modes 'A' and 'C', I suspect, which are not defined as domain values...

Not good, and something to ponder.

**Comment by JanisB-AT** [comment] 2021-02-11 16:16
Ok, you have "Phase 016", I have "Pahse 006" - I've seen those numbers somewhere deep in the code...

**Comment by mbtools** [comment] 2021-02-11 16:34
something changed. MC372 is raised in include RADVIDEP.

It could be Note 2430405 which is valid for 750 only (https://launchpad.support.sap.com/#/notes/2430405). If the change is missing, you could try to apply it manually. If that works, open ticket with SAP to get the note downported.

**Comment by JanisB-AT** [comment] 2021-02-11 18:02
Yeah, and probably quite a bit more of stuff. I doubt it's just that note, and some stuff might never come into notes. 

DDMODE = 'G' + FRCACT = 'X' works fine in 7.40 sp 23, but I still do not get the same "Phase" IDs in the log as you have in 7.50. There is still red 'MC372' in my 'G' mode log [ABAPGIT_20210211_175128.txt](https://github.com/abapGit/abapGit/files/5967471/ABAPGIT_20210211_175128.txt) during TABL activation, but it does not hinder activation, unlike in mode 'O'.

The "Phase" difference, I suspect, should be some changes in [ma_set_operations(RADMASUTC)](https://github.com/JanisB-AT/Test_4496/blob/84b564e598b860f2ffaf9c867084bee493e7565c/src/z_radmasutc_740_sp_23.prog.abap#L272) (I've put the 7.40 code into repo as Z PROG), or somewhere further down in the activation itself, where [acwa]-actmode1/[acwa]-actmode2 could be changing "on the fly".

Could you please attach RADMASUTC 7.50 as a text, so I could try to figure it out (very difficult to work with OSS Notes...)?

I doubt very much now that we'll manage to come up with something that works all the way down to 7.02 (or wherever DD_MASS_ACT_C3 was introduced), though. + FRCACT = 'X' is already an improvement that should hopefully work from 7.50 upwards. Provided, it adjusts the table without data loss, which I'm yet to test.

Trying the 'T' mode, now that I think about it more, can potentially also lead on to very unpredictable path - if the CTS Import Process (something in 'Transport independent' steps, for example) has changed since 7.40. One tricky dependency is better than 3...

**Comment by larshp** [comment] 2021-03-10 06:39
@yellappam was this issue fixed with the TABL format change?

**Comment by g-back** [comment] 2021-03-10 08:37
You can check it out directly with abapgit, Branch -> Switch to PR branch

![image](https://user-images.githubusercontent.com/27279305/110600342-1f8e0780-8184-11eb-9308-e23478c9c56e.png)

**Comment by larshp** [comment] 2021-03-10 09:03
ahh, okay, the PR is https://github.com/abapGit/abapGit/pull/4503

**Comment by mbtools** [comment] 2021-03-10 09:50
See my comment at the end of 4503

**Comment by yellappam** [comment] 2021-03-10 09:55
@mbtools  - You have requested additional changes. Is PR ready to test?

**Comment by yellappam** [comment] 2021-03-10 22:41
Getting below error when trying to switch to PR branch. 

![image](https://user-images.githubusercontent.com/29766214/110707711-913a8400-825e-11eb-92fc-1463158bcba3.png)

**Comment by mbtools** [comment] 2021-03-10 23:41
I think this uses api.github.com which has a different certificate that you have to add to STRUST.

**Comment by yellappam** [comment] 2021-03-11 19:27
Added certificate to the STRUST and still getting same error message. @mbtools  - Could you please create a temporary branch in AG repo using PR so that I will use the branch

**Comment by larshp** [comment] 2021-03-12 11:35
@yellappam you can also use the Advanced -> Change Remote option to change the URL for the repo

**Comment by yellappam** [comment] 2021-03-13 08:46
Stupid me. I forgot this option. Thank you @larshp for the inputs.

**Comment by yellappam** [comment] 2021-03-13 10:14
I have tested the changes and main issue is fixed. Attached the testing document in [#4503](https://github.com/abapGit/abapGit/pull/4503)

**Comment by mbtools** [comment] 2021-03-17 21:57
fyi, march 4 and march 12 2021 github changed SSL certificates. upload root, intermediate, github.com and api.github.com again to strust

**Closed** 2021-03-22 12:12 UTC
Labels: bug
