### ISSUE TITLE
Activation of ABAP DCLS objects via ADT approach

### ISSUE THREAD

**Issue by misik-sap** [abapGit/abapGit#1264] opened 2018-03-22 09:22 UTC
We have encountered various situations, when the activation process of DCLS objects (ABAP Data Control Language Sources) behaves abnormally:

1. the DCLS object remains inactive in the system after the PULL operation in ABAP Git

2. the DCLS object is activated after the PULL operation in ABAP Git, however it is not included in any transport request

We would like to try a different approach:
- we analyzed, how the DCLS objects are activated from ADT (ABAP development tools -- eclipse). Any operation called from eclipse (lock, unlock, activation, ...) calls the RFC FM **SADT_REST_RFC_ENDPOINT**. We would like to reuse the functionality behind this function module in order to enhance the activation process of DCLS objects.

**Comment by larshp** [comment] 2018-03-22 09:28
ok

sounds good, pull requests welcome 😄

**Comment by misik-sap** [comment] 2018-03-22 21:55
Sounds good. I agree with your proposal. We will need to analyze FM: SADT_REST_RFC_ENDPOINT in more detail, in order to extract the corresponding handler class.

**Comment by jfilak** [comment] 2018-06-07 14:16
The point 2 is addressed in #1466

**Comment by christianguenter2** [comment] 2018-06-07 19:55
Point 1 seems to be also a problem of the new experimental DDIC activation. Is this your scenario? I don't have the problem with experimental features deactivated.

When experimental features are activated I get this error. And the DCLS isn't activated nor created.
![image](https://user-images.githubusercontent.com/17437789/41122584-5111fa16-6a9c-11e8-8c66-2ed50ae6bbf8.png)

LT_GENTAB is cleared inside the FM. If I jump over the exception then everything is activated properly.
![image](https://user-images.githubusercontent.com/17437789/41122660-8aeea388-6a9c-11e8-944a-72c52d3840a0.png)

Maybe we should just ignore the 
`no_objects     = 2`
case?

#1055

**Comment by larshp** [comment] 2020-09-23 11:17
@misik-sap can you help reproducing this in a public repository?

**Comment by larshp** [comment] 2020-11-17 12:30
closing, no reply

**Closed by larshp** 2020-11-17 12:30 UTC
Labels: bug
