### ISSUE TITLE
SRVB - Import of SERVICE BINDING

### ISSUE THREAD

**Issue by anagarcigm** [abapGit/abapGit#3443] opened 2020-06-02 17:17 UTC
When I do a pull of a proyect with a service defition. The system doesn´t show any errors.

After If I include the service binding, the system shows an error with service binding.

In eclipse i see that although the service definition is right, it is not activated.
I resolve this situation, activating first the service definition and after service binding manually.
I attached two screens. Appears activated zsd_vuelos but it isn´t,

![zvuelos](https://user-images.githubusercontent.com/56394203/83549460-a3380b00-a505-11ea-91a3-66796c1b14d6.PNG)
![SERVICE_BINDINGS](https://user-images.githubusercontent.com/56394203/83549468-a632fb80-a505-11ea-845a-3c636e0908b3.PNG)

**Comment by larshp** [comment] 2020-06-02 17:19
what type and versions are the source and target systems?

**Comment by anagarcigm** [comment] 2020-06-02 17:29
Both systems have the same version.
I don´t know if this is the information that you need-
S4HANA ON PREMISE	1909
ABAP PLATFORM	     1909
SAP S/4HANA FOUNDATION	1909


Thanks in advance

**Comment by larshp** [comment] 2020-06-02 17:45
is it possible for you to reproduce the example in a public repository?

**Comment by christianguenter2** [comment] 2020-06-02 17:46
Can you supply a publicly available repository to reproduce the error?

**Comment by anagarcigm** [comment] 2020-06-03 07:10
Good Morning,
I have this repository with all the objects.
https://github.com/anagarcigm/FLIGHTS.git
I have attached files too.
Thanks in advance.
Best regards.
[FLIGHTS-master.zip](https://github.com/larshp/abapGit/files/4721518/FLIGHTS-master.zip)

**Comment by christianguenter2** [comment] 2020-06-06 11:47
@anagarcigm 
I can't reproduce your issue with the supplied online repository on my S4/HANA 1909 system. Can you? 
What confuses me is that there is no .abapgit.xml in the repo and why is the no .baseinfo file for the DDLS object as it should be if the source system is 1909?

**Comment by anagarcigm** [comment] 2020-06-07 20:20
Hi, 
It´s true. I have added .abapgit.xml. 
About the .baseinfo fil, with what object is generated?

Haven´t you an error about the ZSB_VUELOS? (Like in my image)
Best regards.

**Comment by christianguenter2** [comment] 2020-06-08 07:21
I have no error in abapGit but in eclipse the service binding has the same three errors as shown in your screenshot. Bug confirmed.

The .baseinfo is generated for the DDLS object. But it has nothing to do with the issue. I just wondered why it isn't there in your repo.

**Comment by anagarcigm** [comment] 2020-06-11 07:49
Hi christian.

Can you tell me if the object zsb_vuelos is saved in your transport order? In my system this objest it isn´t
I don´t know why appears "no transport request given" in program zabapgit.
Best regards.

**Comment by ThomasPloski** [comment] 2021-01-26 09:17
In process

**Comment by larshp** [comment] 2021-12-21 10:53
merged, try again, latest version

**Comment by mbtools** [comment] 2022-03-03 10:57
also #5218 and #5344

**Closed by mbtools** 2022-03-03 10:57 UTC
Labels: bug
