### ISSUE TITLE
ASSERTION_FAILED in ZCL_ABAPGIT_OBJECT_ENHO_WDYC Line 31

### ISSUE THREAD

**Issue by geekblog-dev** [abapGit/abapGit#3586] opened 2020-07-05 07:04 UTC
So line 31 says
ASSERT 0 = 1

In Modul ZIF_ABAPGIT_OBJECT_ENHO-DESERIALIZE

```
TRY
       cl_enh_factory=>create_enhancement(
           EXPORTING
                enhname = lv_enhname
                enhtype = ''
                enhtooltype = cl_wdr_cfg_enhancement=>tooltype
           IMPORTING
                enhancement = li_tool
          CHANGING
               devclass = lv_package ).
       lo_wdyconf ?= li_tool.
* todo
* io_xml->read_xml()
* CL_WDR_CFG_PERSIYTENCE_UTILS=>COMP_XML_TO_TABLES( )
* lo_wdyconf->set_enhancement_data ( )
      ASSERT 0 = 1.
                
```

Not quite sure if it's not totally supported or this is a Bug or both.

**Comment by larshp** [comment] 2020-07-11 10:45
thanks, how can the issue be reproduced?

**Comment by larshp** [comment] 2020-08-18 05:53
guess the reference is https://github.com/larshp/abapGit/blob/db6f21f78c316d215a760e0455c0fb617c4a1bb7/src/objects/zcl_abapgit_object_enho_wdyc.clas.abap#L36

looks like ENHO for WDYC are not fully implemented yet, pull requests welcome

**Comment by mbtools** [comment] 2020-12-15 02:18
I implemented the missing part. @geekblog-dev do you have a repo to test this?

**Comment by mbtools** [comment] 2020-12-28 23:35
Tested with https://github.com/abapGit-tests/ENHO-WDYC. One issue during uninstall which is fixed with https://github.com/abapGit/abapGit/pull/4359. Works fine otherwise.

**Closed by mbtools** 2020-12-28 23:35 UTC
Labels: bug
