### ISSUE TITLE
Shared Memory Area Serialization

### ISSUE THREAD

**Issue by nomssi** [abapGit/abapGit#1201] opened 2018-02-14 10:32 UTC
Hi,

trying to import Shared Memory Area will bring an error message "Error serializing SHMA".
The object is not created properly in the system. I see a helper class ZCL_ABAPGIT_SHMA_HELPER is needed. How to install it?

best regards,
JNN

**Comment by larshp** [comment] 2018-02-14 11:57
hmm, not sure

https://github.com/larshp/abapGit/blob/master/src/objects/zcl_abapgit_object_shma.clas.abap#L49

@christianguenter2 can you help?

**Comment by larshp** [comment] 2018-02-14 12:04
try changing to "LCL_SHMA_HELPER" instead of "ZCL_ABAPGIT_SHMA_HELPER", looks like a copy/paste error when moving to global classes

original code: https://github.com/larshp/abapGit/pull/899/files

**Comment by larshp** [comment] 2018-02-14 14:44
@nomssi try again, latest version

**Comment by nomssi** [comment] 2018-02-16 12:16
mixed results:
I still have a syntax error in the created root class (formal parameter INST_NAME does not exist in method GET_INSTANCE_INFOS). I can get it to work from there, in some systems just by repeating the  zip-mport. I could not test with a pull yet. I will repeat the test once I have staged with the new version.

**Comment by nomssi** [comment] 2018-02-20 14:26
It seems to me that once the Shared Memory Area class is corrupted (e.g. syntax error), it cannot be fixed by abapGit and I have to use transaction SHMA.

**Comment by christianguenter2** [comment] 2018-02-21 15:51
@nomssi 
Can you reproduce the error? If yes I can look into it.

**Comment by larshp** [comment] 2018-03-19 18:51
I guess it is:
1: create SHMA, push it to git
2: introduce syntax error
3: reset local => error?

**Comment by larshp** [comment] 2018-05-10 07:33
@nomssi

**Comment by nomssi** [comment] 2018-05-16 19:06
Method IF_SHM_TRACE~TRIN_GET_INSTANCE_INFOS( ) of class CL_SHM_TRACE_ADAPTER has an optional parameter INST_NAME in newer systems like 7.50 that does not exist in e.g. 7.40 SP08. The generated code uses this parameter, so I always have to generate the area class with transaction SHMA again or suffer a short dump.

**Comment by mbtools** [comment] 2020-07-15 21:44
Old issue but seems changing no_class_generation to false could solve it:

```
ZCL_ABAPGIT_OBJECT_SHMA
ZIF_ABAPGIT_OBJECT~DESERIALIZE
...
        CALL METHOD ('\PROGRAM=SAPLSHMA\CLASS=LCL_SHMA_HELPER')=>('INSERT_AREA')
          EXPORTING
            area_name           = lv_area_name
            attributes          = ls_area_attributes
            force_overwrite     = abap_true
            no_class_generation = abap_false  "<<< force generation
            silent_mode         = abap_true.
```

**Comment by larshp** [comment] 2020-10-09 11:13
@nomssi try again, latest version

**Closed** 2020-10-09 11:13 UTC
Labels: bug
