### ISSUE TITLE
Changes to Method's in Classes not being assigned to the Selected Transport in 1.118.0 or 1.119

### ISSUE THREAD

**Issue by ZagGregH** [abapGit/abapGit#5920] opened 2022-12-08 00:34 UTC
When we first identified this problem, we were using ABAPGit version 1.118.0. In hopes of it being fixed, we upgraded our standalone to 1.119.0, and pulled to that version in our full application. 

We are able to replicate this by pushing a change to an existing method from our local branch to the remote repository, then pulling from our ABAPGit. We are prompted to select a transport to add the changes to, and when we do so and accept, the changes do not get added to the transport. Class Headers are being added appropriately, so are method signature changes.

The information from our debug info is as follows:
<img width="209" alt="image" src="https://user-images.githubusercontent.com/86337888/206328377-48864cf2-ee10-4616-98c1-5a929818e686.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/86337888/206328401-87ed1c0b-a11e-458b-ad5c-8e6001b7cefe.png">
<img width="678" alt="image" src="https://user-images.githubusercontent.com/86337888/206328437-d3da6815-73d1-4602-9deb-9ab3bbed066b.png">
We have tried this version with Experimental Features off and Experimental Features on, both share the same issue.

We changed the tag for our abapGit in the meantime so that we are using version 1.117.0, which is working to bring the changes through to the transport request.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/86337888/206328781-e3fa34b6-68a7-4c30-ae15-aa26d3feb687.png">
After changing the tags to being as indicated above, we are able to replicate the issue in our standalone application and the issue does not occur in our full application.

**Comment by larshp** [comment] 2022-12-08 14:52
I'm unable to reproduce the issue, I've created 
https://github.com/larshp/method_change/
with two branches, `main` and `branch`, switching between these updates a method

![image](https://user-images.githubusercontent.com/5888506/206477744-d4903b15-8d0b-4648-9fee-87e4c2c465f0.png)

![image](https://user-images.githubusercontent.com/5888506/206477759-43d1daed-5937-425a-96c2-d0b989f90a19.png)

![image](https://user-images.githubusercontent.com/5888506/206477833-37b5d214-c2fa-40b3-b444-91ff88c70112.png)

**Comment by larshp** [comment] 2022-12-08 14:57
@ZagGregH can you try reproducing the issue in a public repository? just add some dummy code

**Comment by ZagGregH** [comment] 2022-12-08 20:45
Thanks for looking into this Lars, and for your timely reply.

I have worked through your recommended test case, using your repository as the example, and the issue is still occurring. It seems strange that this would work for you and not for me. 
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/86337888/206562827-986dc38c-c7a9-4433-945d-81ac11bc4ba6.png">
<img width="1878" alt="image" src="https://user-images.githubusercontent.com/86337888/206562891-bf777b94-2c68-447c-badc-66c40238af24.png">
<img width="992" alt="image" src="https://user-images.githubusercontent.com/86337888/206563065-df7e963b-d290-467b-8e01-80212e0e548c.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/86337888/206563363-5802c9b3-8ce3-4841-b2e5-781e3ba48091.png">
 
If there are any further details I can provide to further narrow this down, please let me know and I will get back to you with them.

**Comment by larshp** [comment] 2022-12-14 14:05
anything special in the package setup, regarding the transport layer?

**Comment by ZagGregH** [comment] 2022-12-14 21:30
I dont think there is anything special in our Setup, but here are some images of the transport routes and the package.
<img width="289" alt="image" src="https://user-images.githubusercontent.com/86337888/207710942-50b993c3-2d07-4b1c-b878-f2a58090cae3.png">
<img width="719" alt="image" src="https://user-images.githubusercontent.com/86337888/207711103-a52bccfd-a31f-4045-b37d-53a7a3778ea4.png">

**Comment by Bituix** [comment] 2023-02-01 22:41
I am getting the same issue  with 1.121.0 - Developer Version. Looks like for every Pull the changed objects are not being added to the transport.

In the past when I change a method the whole class was added to a TR with R3TR CLAS, but now  if I change a method nothing in being added to a TR.  I am adding  all objects using 'Advanced > Add All Objects to Transport' or adding manually to the transport.

**Comment by larshp** [comment] 2023-02-07 17:07
@ZagGregH can you try testing https://github.com/abapGit/abapGit/pull/6047

**Comment by ZagGregH** [comment] 2023-02-07 23:35
I have tested #6047 and it worked! 
I made a change to a class method, pulled, checked the Transport I assigned it to and it was there.

**Comment by mbtools** [comment] 2023-02-08 11:46
thanks for testing. the change has been merged

**Closed by mbtools** 2023-02-08 11:46 UTC
Labels: question
