### ISSUE TITLE
DCLS: deserialize fails if gtadir already exists

### ISSUE THREAD

**Issue by jfilak** [abapGit/abapGit#1469] opened 2018-06-07 16:42 UTC
The function tadir_insert do not check if the object exists in gtadir and if it exists, the call dies with an error.
Unfortunately, the method cl_dd_utilities=>write_tadir do not accept DCLS but we can copy the approach.

If gtadir exists and we skip tadir_inser in DCLS~deserialize, the corresponding tadir entry is created during activation.

**Comment by larshp** [comment] 2020-09-23 11:15
I think GTADIR is used only inside SAP, so its not easy to reproduce in normal systems

pull requests welcome

**Comment by mbtools** [comment] 2020-12-28 23:40
If SAP wants this fixed, please create a PR since no one else is using GTADIR feature. Closing.

**Closed by mbtools** 2020-12-28 23:40 UTC
Labels: bug
