### ISSUE TITLE
ASSERTION_FAILED PROCESS_STAGE_LIST when using object filter

### ISSUE THREAD

**Issue by Eikir** [abapGit/abapGit#2482] opened 2019-03-04 15:35 UTC
I've got the same error as described in #803.
AbapGit dumps in stage list when using the filter and having a large number of objects (in my case 1219 and 110 objects).
I was able to reproduce the behavior in two apapGit projects.

Steps to reproduce:
1. Open "stage"
2. At table header click on "add" to mark all objects as to be added
3. Filter objects by name
4. Click on "reset" for one object
5. Click "commit (NUMBER OF OBJECTS)"
6. Dump

It does not dump, when filtering is **not** used. I searched the files by CRTL + F and reset the exact same files as before when using the filter. It does not dump in this case.

Using this approach I was able to commit 1177 out of 1219 objects. 
There are 42 objects left. For them I was not able to reproduce the behavior. So maybe it has something to do with the amount of objects.

---

Short Text: The ASSERT condition was violated.
Category:  ABAP programming error
Runtime Errors: ASSERTION_FAILED
Method:  process_stage_list

Source Code Extract:
```
26532   METHOD process_stage_list.
26533
26534     DATA: lv_string TYPE string,
26535           lt_fields TYPE tihttpnvp,
26536           ls_file   TYPE zif_abapgit_definitions=>ty_file.
26537
26538     FIELD-SYMBOLS: <ls_file> LIKE LINE OF ms_files-local,
26539                    <ls_item> LIKE LINE OF lt_fields.
26540
26541     CONCATENATE LINES OF it_postdata INTO lv_string.
26542     lt_fields = zcl_abapgit_html_action_utils=>parse_fields( lv_string ).
26543
26544     IF lines( lt_fields ) = 0.
26545       zcx_abapgit_exception=>raise( 'process_stage_list: empty list' ).
26546     ENDIF.
26547
26548     LOOP AT lt_fields ASSIGNING <ls_item>.
26549
26550       zcl_abapgit_path=>split_file_location(
26551         EXPORTING
26552           iv_fullpath = <ls_item>-name
26553         IMPORTING
26554           ev_path     = ls_file-path
26555           ev_filename = ls_file-filename ).
26556
26557       CASE <ls_item>-value.
26558         WHEN zcl_abapgit_stage=>c_method-add.
26559           READ TABLE ms_files-local ASSIGNING <ls_file>
26560             WITH KEY file-path     = ls_file-path
26561                      file-filename = ls_file-filename.
>>>>>           ASSERT sy-subrc = 0.
26563           io_stage->add(    iv_path     = <ls_file>-file-path
26564                             iv_filename = <ls_file>-file-filename
26565                             iv_data     = <ls_file>-file-data ).
26566         WHEN zcl_abapgit_stage=>c_method-ignore.
26567           io_stage->ignore( iv_path     = ls_file-path
26568                             iv_filename = ls_file-filename ).
26569         WHEN zcl_abapgit_stage=>c_method-rm.
26570           io_stage->rm(     iv_path     = ls_file-path
26571                             iv_filename = ls_file-filename ).
26572         WHEN zcl_abapgit_stage=>c_method-skip.
26573           " Do nothing
26574         WHEN OTHERS.
```

**Comment by larshp** [comment] 2019-03-15 11:59
Do you use the Java SAP GUI or Windows?

**Comment by Eikir** [comment] 2019-03-15 12:01
> Do you use the Java SAP GUI or Windows?
SAP GUI for Windows.

**Comment by larshp** [comment] 2019-03-15 12:09
hmm, I was not able to reproduce the issue

**Comment by Eikir** [comment] 2019-03-15 12:15
Back then I had SAP GUI 750 and now I do have 760. Error still exists. I was able to reproduce it. I just checked.

Is there anything I can provide to make it easier for you?

**Comment by mbtools** [comment] 2020-08-02 16:31
Probably fixed by https://github.com/larshp/abapGit/pull/3624 (v1.98). Can you re-test with this version, pls?

**Comment by mbtools** [comment] 2020-09-25 03:00
No response. Closing

**Closed by mbtools** 2020-09-25 03:00 UTC
Labels: bug
