### ISSUE TITLE
Question - Restoring from Remote Git Repo to SAP System

### ISSUE THREAD

**Issue by grgmani** [abapGit/abapGit#5669] opened 2022-06-29 17:59 UTC
Hi,
I am exploring the abapGit for one my project scenario where I want to move the object from SAP system to remote Git repo.  Also in specific scenario , if there is a request come later for the same object then i would like to restore that object from remote Git repo to SAP system.  I am facing an issue with this  last section of restoring the object from remote repo to SAP,
I have followed the following steps after installing and setting up the abapGit-
1. Move the object to abapGit sync package
2. Execute the program abapGit standalone program
3. Executed the "Stage", selected action "Add" and successfully completed the "Commit".
4. Verify the object is available in the remote repo
5. Deleted the object from SAP system
6. Executed the "Stage", selected action "ignore" and successfully completed the "Commit"..
7. Verify the object is still available in the remote repo and it just deleted from the source system(SAP)
8. Login to remote repo 
9. open the specific abap object that need to be restored
10.  Made the changes in the comment section of the object
11.  Committed the change in the remote repo
12.  Now when i go to the abapGit standalone program execution screen, it doesn't show any changes in the difference section. If i do pull it says that there is no change find between local and remote repo.
13. I tried to remove the object under "Repository" ignore section but still no luck on restoring the object back to SAP.

I may be missing something here but could you please guide me here that how can i restore the object back to SAP.

Thanks

**Comment by christianguenter2** [comment] 2022-06-30 05:47
12. it makes sense that the object doesn't show up as it's still ignored. So works as designed I'd say
13. how does the repo look like after you did that? Works for me. What you also can try is to remove the ignored files from .abapgit.xml in the remote repo and commit.

**Comment by mbtools** [comment] 2022-06-30 07:13
Just remove step 6 and it should work as you expected.

**Comment by grgmani** [comment] 2022-06-30 11:20
Thanks Christian for your reply. After removing the objects from the "Repository ignore section", it does show me difference in the .abagit.xml but don't know what to do next because pull action after that doesn't restore the object back to SAP. I will try, your suggestion to remove ignored files from the remote repo and commit then see if it works.

Thanks Marc for your reply. I can't remove the step 6 because then moment i will delete the object in SAP, it will show the difference in abapGit and these differences increase count will increase based on number of objects deleted and that will make the confusion later on if i do some other adjustments. I just want to keep abapGit view clean( without any difference) after every change i make in the SAP system.

Any other recommendations or details will be helpful here.

**Comment by christianguenter2** [comment] 2022-06-30 11:30
> because pull action after that doesn't restore the object back to SAP.

Hm, that's suspicious. I guess that's because pull also restores .abapgit.xml. Do you see your object as diff after removing it from ignore? Few screenshots would also be helpful to support you.

**Comment by larshp** [comment] 2022-06-30 11:43
@grgmani stepping one step back, what is your scenario? Git will help trying to keep local and remote in sync, if this is not what you want, then do changes in your scenario or setup

**Comment by mbtools** [comment] 2022-06-30 11:44
well, the history is in the git repo! there's no need to ignore anything here. 

delete the object in the SAP system and stage/commit this deletion to the repo. if you want to restore any deleted object, go to the remote repo settings in abapGit and select the commit right before the deletion happened. now you can pull from this commit (point in time). 

Alternatively, you can use branches of course.

**Comment by grgmani** [comment] 2022-06-30 13:01
Thanks again everyone for commenting and providing insights. Let me clarify further and answer to Marc and Lars comment -
1. After deleting the object from SAP and if performing the stage/commit, my understanding is that it will also delete the object from remote repo as well.  I think this align with Lars comment too that Git will help to keep local and remote in sync. So in this case object will get deleted from both SAP and Remote repo which is contrary to my requirement.

My scenario is that I want to delete object in SAP system but doesn't want to get deleted from remote repo and do that , i am using ignore action. With this i was able to achieve all the expected results, 
a. the object is deleted in SAP 
b. it's still available in the remote repo
c. GIT is also clean not showing differences 

Now from my initial question thread, the problem is when you want to restore this object back to SAP from remote repo. Here i want thank Christian for providing the hint and answer to the problem.

Previously, i was only going to Git and through repository settings was removing the required objects from the ignore section and saving the settings. After that it does reflect the difference in the .abagit.xml in the GIT but i believe that's not sufficient enough to restore the object back to SAP. Here if i perform the pull action was restoring the .abapgit.xml back where ignore section is again updated with the objects.
As suggested by Christian, I also need to go to the remote repo and from there .abapgit.xml, i need to remove the objects from it and do commit. Once this step is done then Git will show the object in diff list and after that if i do the pull then object got restored back to SAP successfully.

I believe this is the right procedure to restore the object back to SAP. If you all agree with the given steps then i think we can close this question now.

Thanks everyone for helping me here and providing me the right direction.

**Comment by larshp** [comment] 2022-06-30 13:10
Why dont you want to delete the object in remote? Full history is there, git clients helps keeping things in sync

**Comment by grgmani** [comment] 2022-06-30 13:11
Because i am treating remote repo as my backup repository for the objects.

**Comment by christianguenter2** [comment] 2022-06-30 13:37
> I also need to go to the remote repo and from there .abapgit.xml, i need to remove the objects from it and do commit

Btw. removing the files from Ignore File in abapGit and committing the changes of .abapgit.xml should achieve the same result.

**Comment by christianguenter2** [comment] 2022-06-30 13:44
> Why dont you want to delete the object in remote? Full history is there, git clients helps keeping things in sync

One reason for ignoring deletions rather than committing them might be that some git servers (e.g. our company internal bitbucket server) are not capable of searching through the whole git history (you have to pay for that feature I guess). So bitbucket search won't find the deleted files, which can be quite irritating.

**Comment by mbtools** [comment] 2022-06-30 13:50
Per definition, a git repo is a "backup of everything". so it's absolutely safe to commit a deletion to the git repository. you can always go back and restore any of your deleted objects (as long as they were once committed to the repo, of course). 

Here's an example: 

in https://github.com/abapGit/abapGit/pull/5503/files, I deleted a class and an interface. the corresponding commit is https://github.com/abapGit/abapGit/commit/588fb00cb06e6c013b3ef82a916bf8d70080c4c9

if you navigate to the previous commit (you find it linked as "parent" of 588fb00cb06e6c013b3ef82a916bf8d70080c4c9) you get https://github.com/abapGit/abapGit/tree/375092c37039a838bb4549c077936b533d023d25. You will find the files in the /src/ folder. 

so if I want this class and interface back in my SAP system, I set the commit in abapGit to 375092c37039a838bb4549c077936b533d023d25, run "Advanced > Selective pull", and pick these two objects.

**Comment by grgmani** [comment] 2022-06-30 14:01
@mbtools - how do you set required commit in the abapGit?

**Comment by mbtools** [comment] 2022-06-30 14:19
Repo Settings > Remote > Select "Commit" and enter the commit id (if it's a recent commit you can also use the value help)

https://docs.abapgit.org/settings-remote.html

**Comment by grgmani** [comment] 2022-06-30 17:46
Thanks Marc, your suggest steps also worked. So now i have couple of solution options to choose for restoring the object back to SAP. I will close this issue now.

**Closed** 2022-06-30 17:46 UTC
Labels: question
