### ISSUE TITLE
Missing nice error on similar (duplicate ?) packages

### ISSUE THREAD

**Issue by plsnp** [abapGit/abapGit#4620] opened 2021-03-10 15:06 UTC
1. AbapGit won't open the repository (repo management screen)
2. Dump on the following line https://github.com/abapGit/abapGit/blob/17eac7b6c37eb583544f494ed23a4e750ebd7a5d/src/objects/core/zcl_abapgit_file_status.clas.abap#L296
3. Debugging showed that package.devc.xml was present twice in local (on the same path)
4. Error occurred after sha1 was found for first package.dev.xml it is cleared (next line), then couldn't lookup sha1 for second package.devc.xml (which seems correct)
5. Root cause was two packages with similar name only difference was a single underscore in the name. After removing one of the package problem went away.

I'm not in the situation to further analyze this bug. Might have been related to a messy situation with transport requests.

**Comment by mbtools** [comment] 2021-03-10 20:14
Hmm abapGit is using '_' to separate folders and SAP packages. If your repo is using "prefix" for the folder logic, then package names must not contain other '_' characters. It's better to use "full" for the folder logic in such case. 

Example: 

- `pack1`
- `subpack1` (sub package of `pack1`)

That's ok.

- `pack1`
- `pack1_` or `pack1_pack2` (sub packages of `pack1`) 

Not ok. 

We could extend the validation of an existing package hierarchy if this happens more often.

**Comment by larshp** [comment] 2021-03-12 12:31
@plsnp what are the actual package names to reproduce this error? 

right now we cannot really fix or change anything, as we cannot reproduce the error

**Comment by plsnp** [comment] 2021-03-15 08:41
Hi @larshp how did you try to reproduce ?

**Comment by larshp** [comment] 2021-03-15 09:06
I did _not_ try to reproduce, with the description I can just start guessing and try anything, I don't really feel like spending hours guessing

**Comment by plsnp** [comment] 2021-03-15 10:49
Yes well mbtools made a pretty good guess what could be example package names to reproduce this. I don't think i am at liberty to give the actual package names. But it is similar to "FOO_BARQUX" and "FOO_BAR_QUX". If this information is not sufficient the issue can be closed i guess. I made this ticket not so much for myself (because i have the situation sorted out), rather as a good user of abapGit reporting findings.

**Comment by larshp** [comment] 2021-03-22 12:17
@mbtools do you want to try reproducing this? If not I'll close the issue

**Closed** 2021-04-10 09:26 UTC
