### ISSUE TITLE
Consistent handling of ABAP Language Version during pull/push

### ISSUE THREAD

**Issue by ThomasPloski** [abapGit/abapGit#6154] opened 2023-03-16 10:50 UTC
Dear abapGit community,

With the 7.52 release, SAP provides the usage of the ALV (ABAP language version) information in the onPrem world. 

In order to support a consistent handling of the ALV across the different abapGit "flavours" (Open Source / part of SAP BTP ABAP), we are currently working on a concept/proposal (also referring to issue #5921). 

The idea is to use this issue to discuss the topic and its boundary conditions as well as collect feedback. 

Further links: 
https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-US/abenabap_versions.htm
https://help.sap.com/doc/abapdocu_cp_index_htm/CLOUD/en-US/abenabap_versions.htm
https://blogs.sap.com/2022/09/09/abap-language-versions-faqs/

**Comment by larshp** [comment] 2023-03-16 10:59
a. Dont serialize ALV to files
b. During deserialization set the ALV according to the ALV from the package

**Comment by mbtools** [comment] 2023-03-16 11:51
Appreciate the initiative, Thomas 🙏 

a. agree
b. agree, but needs clarification if package does not exist (yet)
c. specify "orignal ALV" and a list of "compatible-with ALVs" in repo settings

**Comment by larshp** [comment] 2023-03-16 11:59
b. IMHO, require users to always create packages manually, we cannot automatically determine things like transport route
c. nice to have

**Comment by fabianlupa** [comment] 2023-03-16 12:33
Somewhat off topic, I am seeing the use of the acronym ALV for ABAP Language Version here for the first time. Is that a fixed term? (Many people might get confused with the ABAP List Viewer :P )

**Comment by BeckerWdf** [comment] 2023-03-16 12:40
> Somewhat off topic, I am seeing the use of the acronym ALV for ABAP Language Version here for the first time. Is that a fixed term? (Many people might get confused with the ABAP List Viewer :P )

Not it is not - but often used inside SAP. It can easily cause confusion because of the ABAP List Viewer. We should not use it here.

**Comment by larshp** [comment] 2023-03-16 13:36
so, it turns out that in on-prem it is possible to have a package with mixed ALVs, ie. ignoring the field in serialization would loose information.

the nice world would be developers using the ALV on package level

so perhaps, by default ignore ALV, but have a setting(in `.abapgit.xml`) which will enable serialization of the field

hmm

**Comment by BeckerWdf** [comment] 2023-03-16 13:41
The language version on package level is just the "default" when creating new development objects in that package.
But the language version of individual development objects can be change to other language versions. AFAIK each package (or software component) also contains a list of allowed language versions. When you try to change the language version it is checked if the package / sw component does allow it and if you have the needed authorization for it.

**Comment by anfisc** [comment] 2023-03-16 14:14
The language version "ABAP for cloud development" on package level is enforced if the package is part of a software component that uses ABAP language version 5.  
[Setup Developer Extensibility](https://help.sap.com/docs/ABAP_PLATFORM_NEW/ed0e11412f9841e7ac5cd9a6799368d4/8da870021323498db15a1c56cfc9b302.html?locale=en-US)

**Comment by schneidermic0** [comment] 2023-03-17 07:12
Just as a reference. There was a discussion on the topic related to ABAP language version and ABAP file formats in issue https://github.com/SAP/abap-file-formats/issues/44

**Comment by schneidermic0** [comment] 2023-03-17 07:32
> so, it turns out that in on-prem it is possible to have a package with mixed ALVs, ie. ignoring the field in serialization would loose information.

Yes, this is possible. @BeckerWdf confirmed the same. This was also the reason why I wanted this field (at least as optional information) per object in the ABAP file formats. There we need the possibility to ensure to keep the ABAP language version of an object.

I guess, it wouldn't be an issue to specify the ABAP language version per object (as it is for other object-specific property) if there weren't the need to work with repositories in different releases (releases which support the ABAP language version as property and releases which don't). 

This situation would lead to the fact that abapGit serializes object differently (dependent on the release). Same situation as for other fields which might be introduced in later releases, but are unknown in lower releases. Since ABAP language version affects a broad range of object types this might lead to diffs for almost all objects in a repository. :(

**Comment by schneidermic0** [comment] 2023-03-17 07:43
> so perhaps, by default ignore ALV, but have a setting(in .abapgit.xml) which will enable serialization of the field

I am in favour in storing the ABAP language version per object (since it is a property of the object). However, I can understand the issue with the serialization/large diffs. Therefore, I guess @larshp's proposal to provide a configuration in the repository could be a solution for abapGit.

If this approach is taken, we should be aware of the implications if no ABAP language version is *not* serialized (due to the setting):

1. There is no option to have mixed ABAP language version in a repository
2. If we don't store any further information (e.g., in the repository) which ABAP language versions the objects shall get. The ABAP language version might not be set in the target system. If we take up the approach of set this information manually on the root package of the repository, each developer would have to set it manually
3. If the ABAP language version for the repository is not consistent specified (at least for systems which support the ABAP language version ;), developers might use functionality which are not supported for ABAP language version to be used in ABAP Cloud. I.e., they might introduce usages of non-released APIs or use statements which are not allowed in ABAP Cloud.
4. Most probably there are further implications ;)

In any case, we would need a clear contract for abapGit how objects are deserialized in systems which support ABAP language version if the ABAP language version was not specified for the object.

**Comment by fabianlupa** [comment] 2023-03-17 07:46
> This situation would lead to the fact that abapGit serializes object differently (dependent on the release). Same situation as for other fields which might be introduced in later releases, but are unknown in lower releases. Since ABAP language version affects a broad range of object types this might lead to diffs for almost all objects in a repository. :(

Maybe if the field is not available, serialize ABAP Language Version "Standard ABAP", if it is available, serialize the one in the system? Then we'll have a one time diff for every repo when this logic is applied, but not on each pull / commit when a repo is used in two different systems.

**Comment by larshp** [comment] 2023-03-17 07:51
We want to build an ecosystem where its easy to share and contribute to code.

Eg. if I implement a cool Fibonacci algorithm in 702, then it should be possible to pull it to Steampunk, and vice versa, without causing too many diffs.

Currently abapGit does not enforce/carry information as to which syntax or statements that are used, its a job for CI to check.

Also, what are the recommendations from SAP on how to build nice systems, eg. I'd guess its nice to have ALV enforced via the software component? Whereas having mixed ALVs should not be a recommended setup?

**Comment by schneidermic0** [comment] 2023-03-17 07:53
> Maybe if the field is not available, serialize ABAP Language Version "Standard ABAP", if it is available, serialize the one in the system? Then we'll have a one time diff for every repo when this logic is applied, but not on each pull / commit when a repo is used in two different systems.

I had following situation in mind: One developer works in a system which supports ABAP language version (e.g. in the Cloud or releases >= 7.52) and another developer in a system which doesn't support it (e.g. 7.50). 
If the objects are developed in ABAP language version for ABAP Cloud, the one system would set `"abapLanguageVersion": "cloudDevelopment"`, the other would set it either to `"abapLanguageVersion": "standard"` or wouldn't serialize the value at all. 

This would lead to a diff for all affected object, wouldn't it?

**Comment by schneidermic0** [comment] 2023-03-17 08:03
> Also, what are the recommendations from SAP on how to build nice systems, eg. I'd guess it's nice to have ALV enforced via the software component? Whereas having mixed ALVs should not be a recommended setup?

Recommendation is to go for "ABAP Cloud" and not mixed (per software component). ;)
See also https://www.sap.com/documents/2022/10/52e0cd9b-497e-0010-bca6-c68f7e60039b.html

**Comment by mbtools** [comment] 2023-03-17 11:14
SAP offers max flexibility by allowing a different ALV for each object. Mixing ALVs in package/swc might be necessary to support SAP legacy scenarios but that does not mean it's a good practice for custom developments nor does it mean that abapGit must support such questionable practices. 

It's similar to the "original language" of objects. Sure you could mix English, German, and French objects in a package. But it's not a good idea. For abapGit we decided to define/fix the main language at repo level which enforces the good practice. 

Is there any reasonable use case where a repo must support mixed ALVs (note: different branches can still have different settings)? If not, there's no need for abapGit to support it.

How about these options for a repository setting:

- Standard: Repo is limited to on-prem (won't work on Steampunk)
- Key user: Repo is limited to key user extensibility
- Cloud: Repo is limited to BTP and embedded Steampunk (won't work on-prem)
- Cross-platform: Repo is compatible with on-prem and Steampunk

When serializing, objects with an ALV that does not match the repo settings are marked as "not supported" (handled the same as unsupported object types). 

When deserializing objects, ALV is set according to the following rules:

- Standard, Key User, & Cloud: 
  - If target package does not exist, set ALV to the repo ALV
  - If target package already exists and does not match the repo ALV, raise error
- Cross-platform:
  - If target package does not exist, set ALV to the ALV supported by the system 
    - If system supports exactly one ALV,  set ALV accordingly
    - If system supports multiple ALV, raise error and ask user to create target package with the desired ALV
    - If system does not support ALV, deserialize without ALV
  - If target package already exists, set ALV to the ALV of the target package

**Comment by schneidermic0** [comment] 2023-03-17 14:07
> Is there any reasonable use case where a repo must support mixed ALVs (note: different branches can still have different settings)?

I can imagine users want to go for "ABAP Cloud", but it hasn't been possible (yet) to change all code to ABAP cloud. E.g.,  some objects still require to call functionality which is not released by SAP. I am not sure whether you want to move these to a dedicated repository (with a different language version).

> How about these options for a repository setting:
...
Cloud: Repo is limited to BTP and embedded Steampunk (won't work on-prem)
...

Actually, "Cloud" works on-premise, too. This ABAP language version indicates this code can run in the cloud. It does not mean "cloud-only".
Maybe, this is one of the misleading aspects. 

> Cross-platform:
- If target package does not exist, set ALV to the ALV supported by the system
-- If system supports exactly one ALV, set ALV accordingly
-- If system supports multiple ALV, raise error and ask user to create target package with the desired ALV
- If system does not support ALV, deserialize without ALV
-- If target package already exists, set ALV to the ALV of the target package

@mbtools If I I understand your proposal, "cross platform" means it is compatible with both, but you want to set the same ABAP language version for all objects in the repository. Right? 
Can't we set the repository to "Cloud" in this case. Objects would be set to "Cloud" in systems which support ABAP language version "cloudDevelopment", in other systems it is anyhow "standard".

**Comment by anfisc** [comment] 2023-03-17 18:53
When looking at the discussion I see that various versions of terms are used to describe the name of the ABAP language versions. 
When storing ABAP language version as a property for an object I would suggest that the values should follow the names we find in the domain ABAPVRS, namly:
**Standard ABAP**, **ABAP for Cloud Development** and **ABAP for Key Users**
, so we should probably use these values in a camel case like fashion
```
"abapLanguageVersion" : "standardABAP"
"abapLanguageVersion" : "ABAPForCloudDevelopment"
"abapLanguageVersion" : "ABAPForKeyUsers"
```
or in an ABAP style   

```
"abapLanguageVersion" : "standard_abap"
"abapLanguageVersion" : "abap_for_cloud_development"
"abapLanguageVersion" : "abap_for_key_users"
```

**Comment by fabianlupa** [comment] 2023-03-17 19:21
> > Maybe if the field is not available, serialize ABAP Language Version "Standard ABAP", if it is available, serialize the one in the system? Then we'll have a one time diff for every repo when this logic is applied, but not on each pull / commit when a repo is used in two different systems.
> 
> I had following situation in mind: One developer works in a system which supports ABAP language version (e.g. in the Cloud) and another developer in a system which doesn't support it (e.g. 7.50). If the objects are developed in ABAP language version for ABAP Cloud, the one system would set `"abapLanguageVersion": "cloudDevelopment"`, the other would set it either to `"abapLanguageVersion": "standard"` or wouldn't serialize the value at all.
> 
> This would lead to a diff for all affected object, wouldn't it?

Yes, I thought that scenario wouldn't apply as the 750 developer would have to "blindly" develop compatible code without accidentally using unreleased APIs or disabled ABAP statements. But I guess there is other tooling available to check for compatibility without the syntax check which would rely on the ABAP Language Version.

**Comment by mbtools** [comment] 2023-03-17 19:27
@fabianlupa in general true and tooling would be a necessity. at the same time, there are also many "open-source ABAP libraries" to be invented which would not rely on any or only well known APIs.

**Comment by schneidermic0** [comment] 2023-03-19 09:07
> When looking at the discussion I see that various versions of terms are used to describe the name of the ABAP language versions.

I agree, we shouldn't use different terms in the discussion. I suggest to use the same values as they are defined in the ABAP file formats `"standard"`, `"keyUser"`, and `"cloudDevelopment"`.

See https://github.com/SAP/abap-file-formats/blob/ea84f27da76ff525e6262ff1675afe1ef17ba890/file-formats/ddls/ddls-v1.json#L38-L40

**Comment by schneidermic0** [comment] 2023-03-23 10:18
Let me try to summarize the discussion up to now:

There shall be a repository setting which specifies the ABAP language version for all objects in the repository. We see the following values/options for this setting :

- "standard": Repo is limited to on-prem (won't work on Steampunk)
- "keyUser": Repo is limited to key user extensibility
- "cloudDevelopment": Repo consist of ABAP Cloud-ready code. It can potentially also - run on-premise.

Note: I have chosen the same values as we use them already for the `abapLanguageVersion` in ABAP file formats.


There is also the use case of having mixed ABAP language versions. However, this is most probably are rare case that might happen during the migration from "standard" to "cloudDevelopment". Therefore, I understand abapGit won't support it in a first step. This could be added later (if required/desired) by either adding another value to the above mentioned options or by adding an additional repository setting.


The behavior during deserialisation shall be as follows:

The repository configuration defines which ABAP language version shall be set for each repository object during deserialization. This means:

- If the setting of the software component allows the specified ABAP language version, the ABAP language version is deserialized for the object accordingly
- If the setting of the software component does *not* allow the specified ABAP language version, the pull of the object raises an error and the object is not pulled.
- If a system does not support ABAP language versions it will just ignore the repository setting.

**Comment by larshp** [comment] 2023-03-23 10:26
1. If its a field, I suggest it to be optional, and default empty, allowing the community to share code
2. Typically repository specific information is stored in `.abapgit.xml`

**Comment by mbtools** [comment] 2023-03-23 14:58
Some repo settings are read-only (like "original language"). This could work here, too, until a change process is defined and implemented. 

during deserialize the package might not exist. the software component will then depend on the package name:
generally: $ = LOCAL, Y/Z = HOME, but other scenarios are possible

**Comment by anfisc** [comment] 2023-03-23 18:08
With ABAP Cloud the above mentioned naming convention will not fit anymore.  
You can have packages starting with 'Z' that are part of the software component 'ZLOCAL' and other packages whose name starts with 'Z' that are part of 'ZCUSTOM_DEVELOPMENT'.
On prem you can also have packages whose name start with "TEST_" that are part of "LOCAL".

**Comment by anfisc** [comment] 2023-03-23 18:15
> 1. I guess it shall be also allowed to have repositories without specifying the ABAP language version. What shall be the behavior in this case?
>    I guess same behavior as it is today.

The current behavior led to the problem that I have tried to import a GitHub repo in an on premise system in a package of ABAP language version "ABAP for Cloud Development"  and ended up in a dead lock situation. 
The repo did not specify a behavior and ZABAPGIT set the ABAP language version of classes and CDS views to "ABAP standard" though this is not allowed due to the settings of the package / software component in my SAP S/4HANA 2022 system.

**Comment by xtough** [comment] 2023-03-24 06:51
> > 1. I guess it shall be also allowed to have repositories without specifying the ABAP language version. What shall be the behavior in this case?
> >    I guess same behavior as it is today.
> 
> The current behavior led to the problem that I have tried to import a GitHub repo in an on premise system in a package of ABAP language version "ABAP for Cloud Development" and ended up in a dead lock situation. The repo did not specify a behavior and ZABAPGIT set the ABAP language version of classes and CDS views to "ABAP standard" though this is not allowed due to the settings of the package / software component in my SAP S/4HANA 2022 system.

That was a misunderstanding. In your case, @anfisc,  the repo would bear the setting "cloudDevelopment", because you originally created it from a Steampunk/Cloud system. On-premise, the import target package should be assigned upfront to a "cloudDevelopment" SWC. Then  all objects would be imported as "cloudDevelopment". 

Even if you would import the repo on-premise into an arbitrary different package, even if it is not assigned to any SWC, the ABAP language version "cloudDevelopment" would still be set for all objects (if the target system's release supports this), because objects with "cloudDevelopment" can still live in "standard" packages.

@schneidermic0 Correct?

What we *should be more precise* on is the behavior when importing repos w\o specified ABAP language version. Should the behavior of deserialization also depend on the SWC assignment of the target package?: If the target package belongs to an SWC where only "cloudDevelopment" is allowed, would import: 
a) attempt to set "cloudDevelopment" to all objects (and maybe fail for some individually), or
b) fail immediately for all because SWC for "cloudDevelopment" allow no other ABAP language versions?

I would vote for a). 

In the end we have a 2x2 matrix of possibilities for which we need to specify the desired behavior *for both, import and export*:
1. repository: undefined/"standard"  -- System/SWC: undefined/"standard"
2. repository: undefined/"standard" -- SWC: "cloudDevelopment"
3. repository: "cloudDevelopment" -- System/SWC: undefined/"standard"
4. repository: "cloudDevelopment" -- SWC: "cloudDevelopment"

**Comment by schneidermic0** [comment] 2023-03-24 07:20
> Even if you would import the repo on-premise into an arbitrary different package, even if it is not assigned to any SWC, the ABAP language version "cloudDevelopment" would still be set for all objects (if the target system's release supports this), because objects with "cloudDevelopment" can still live in "standard" packages.
@schneidermic0 Correct?

Yes, this is also my understanding.

**Comment by schneidermic0** [comment] 2023-04-11 15:08
I went through the different options, I think we can reduce @xtough's 2x2 matrix to 3 options we need to differentiate:

1. repository: ABAP language version is *undefined*
2. repository: ABAP language version is *defined* -- System/SWC has *same* or undefined ABAP language version as specified in the repository
3. repository: ABAP language version is *defined* -- System/SWC has *different* ABAP language version as in the repository

If my understanding is correct, I think there have been proposals for the *import* of these options in this issue:

1. *undefined*: Set the default ABAP language version of the system/ software component; see https://github.com/abapGit/abapGit/issues/6154#issuecomment-1482335573
2. *same*: Set ABAP language version to repo's ABAP language version
3. *different*: Raise error

I think the behavior of the *export* will be the same in all situations. The objects are just serialized without ABAP language version to the abapGit repository.

However, I still see following open question:

1. How do we handle changes to the repository setting? E.g., introducing the repository setting "abapLanguageVersion": "cloudDevelopment", but the objects have already been pulled into a user's system. Since, there won't be a diff in the objects some special handling would have to change the ABAP language version for all objects that already exist in the system with the wrong/old ABAP language version?

2. What is the import behavior in systems which don't support ABAP language version at all, but the repo specifies ABAP language version (not "standard")? Does abapGit raise an error or does it just import it (without setting the ABAP language version)?

**Comment by jfilak** [comment] 2023-04-11 15:26
> How do we handle changes to the repository setting?

Fork, rename, ask users to migrate - since you are redefining where the project can be run and what it can do.

BTW: IMHO mixed ABAP versions in one package/repository just lets the mess in ABAP packaging grow further. Let's teach ABAPers that source codes are not their pets (can be moved, renamed) and push ABAPers to be better in packaging - defining components not just blindly throwing bits into a bucket.

**Comment by mbtools** [comment] 2023-04-11 15:52
> How do we handle changes to the repository setting?

There will be a diff on `.abapgit.xml`. Pulling should raise an error. User can uninstall and reinstall. Or wait until we define a change process in AG.

> What is the import behavior in systems which don't support ABAP language version at all

If the repo is "cloudDevelopment", importing into an old release should raise an error right away since it's unlikely to work (ABAP syntax, steampunk libs, etc).

**Comment by larshp** [comment] 2023-04-27 12:12
todo, update https://docs.abapgit.org/development/serializers.html

**Comment by ThomasPloski** [comment] 2023-07-13 09:23
Just want to give you a short overview about the raised pull requests:

1. Introduce ABAP Language Version as repository setting in .abapgit.xml without no implication to the current behavior. Pull Request #6335
3. Introduce ABAP Language Version functionality as part of new class zcl_abapgit_abap_language_vers to check whether an import can be performed based on the the repository settings and package respective software component settings.
4. Call IS_IMPORT_ALLOWED check within import logic (no change to current behaviour)
5. Call GET_ABAP_LANGUAGE_VERS_BY_OBJT for to be deserialized object

**Comment by schneidermic0** [comment] 2023-10-05 15:01
Object types supporting ABAP language version: 

ADVC, AIFC, AOBJ, APLO, AUTH, BDEF, BGQC, CACC, CCAC, CDBO, CFDA, CGRC, CHDO, CHKC, CHKE, CHKO, CHKV, CLAS, DCLS, DDLS, DDLX, DEVC, DMON, DOBJ, DOMA, DRAS, DRTY, DSFD, DSFI, DTDC, DTEB, DTEL, EEEC, EEEP, ENHO, ENHS, ENQU, EVTB, FUGR, G4BA, G4BS, GCPM, GSMP, HTTP, ILMB, INA1, INTF, IWMO, IWOM, IWSG, IWSV, IWVB, LRCC, NONT, NROB, NTTA, NTTY, OA2S, PCFN, RONT, SAJC, SAJT, SKTD, SMBC, SMIM, SOD1, SOD2, SQL1, SRVB, SRVC, SRVD, SUSH, SUSO, TABL, TOBJ, TRPR, TTYP, UIAD, WAPA, WB2J, WMPC, XINX, XSLT

**Comment by mbtools** [comment] 2023-10-05 17:02
Included in #6476: 
CLAS, DEVC, FUGR, INTF, PROG

Supported by abapGit but will need ALAV handling:
AIFC, AUTH, BDEF, CHDO, DCLS, DDLS, DDLX, DOMA, DTDC, DTEL, ENHO, ENHS, ENQU, G4BA, G4BS, IWMO, IWOM, IWSG, IWSV, IWVB, NROB, SKTD, SMIM, SRVB, SRVD, SUSH, SUSO, TABL, TOBJ, TTYP, WAPA, XINX, XSLT

**Comment by mbtools** [comment] 2023-11-01 12:52
Hello Everyone,

with great effort (#6298, #6476), abapGit is now able to handle ABAP Language Version end-to-end. It's still behind a feature switch and support is limited to the object types listed in the previous comment but should work well otherwise.

Please go ahead and test. 

Best,
Marc

**Comment by mbtools** [comment] 2023-11-16 15:51
Ref https://github.com/abapGit/docs.abapgit.org/pull/184 

Issues:

1. Consistency: "Any" serialized ALaV for classic objects but not for AFF
2. Compatibility: AFF in AG does not serialize ALaV but other SAP tools would contain it (can't exchange files)
3. Diffs: Since "Any" contains ALaV in metadata, importing might show diffs 

Suggestion:

- "Any": Always serialize ALaV
- AFF:  Always serialize ALaV
- New mode "None" (no ALaV): Never serialize ALaV ("Lars Mode"), import sets ALaV based on root package
   This might or might not work for a given object. But there won't be diffs.

**Comment by xtough** [comment] 2023-11-17 14:27
After some internal discussions on how to deal with this repo-setting on Steampunk, we came to a similar proposal like the "Lars Mode":

- import any repo, log warning in case repo ALaV is not "Cloud", set ALaV on all objects to "Cloud" upon **inactive** import --> ABAP Cloud rule violations will surface upon activation in target system (this allows initial import of non-cloud "legacy" code to Steampunk)
- export to any repo, log warning in case repo ALaV is not "Cloud", set ALaV on repo to "Cloud", never write ALaV to individual objects (to avoid unnecessary deltas)

We are aware that the 2nd part leaves a bad taste in the mouth but it still seems the better alternative. Otherwise developers intending to use [tier 1 extensibility](https://www.sap.com/documents/2022/10/52e0cd9b-497e-0010-bca6-c68f7e60039b.html) (ABAP Cloud compliant) also in SAP S/4HANA Private Cloud Edition or on-premise would have to be mindful to explicitly set their abapGit repo to "Cloud". If they forgot this small but important step, the ALaV setting on individual objects will be missing on the target system and the whole application will not be usable.

**Comment by mbtools** [comment] 2023-12-08 15:29
Closing this with https://github.com/abapGit/abapGit/issues/6689 as a follow-up

Any problems, just create a new issue

**Closed by mbtools** 2023-12-08 15:29 UTC
Labels: serialization, discussion
