### ISSUE TITLE
ABAP BTP - system exception ERROR_MESSAGE during Pull

### ISSUE THREAD

**Issue by tmackowski** [abapGit/abapGit#5978] opened 2023-01-09 11:18 UTC
I'm using abapGit to import code from on-premise to ABAP BTP.
During pull I'm getting following error:
 Pull aborted: Repository pull aborted - Job canceled after system exception ERROR_MESSAGE
 Please check status and message for all imported ABAP objects

There are no additional errors or details. How can I find the root cause?

![image](https://user-images.githubusercontent.com/10130130/211296522-40955c84-08f1-4605-805f-0bd7455ecc83.png)

**Comment by mbtools** [comment] 2023-01-09 11:33
First, it looks like a bigger project. Does pulling work with a small test repo like https://github.com/abapGit-tests/CLAS?

Second, what objects are listed under the first node `(12)`?

**Comment by tmackowski** [comment] 2023-01-09 11:54
Yes, It's a bigger project (~3500 objects) . I used it without issues for smaller projects for the same system combination.

![image](https://user-images.githubusercontent.com/10130130/211302282-0d7b28df-f644-4235-ae91-4cf44d831e25.png)

**Comment by mbtools** [comment] 2023-01-09 14:23
the warnings are about objects that were assigned to a different package. AG handles those nicely. 

Using the abapGit ADT plugin makes it difficult to determine the root cause here since it's a quite generic error message. I see you have 20 packages. Devide an conquer. Try defining smaller repos for individual packages. That should help narrow down what causes the problem.

**Comment by tmackowski** [comment] 2023-01-09 14:32
I had also unsupported types in other/smaller packages and they were just ignored.
I'll try to import in smaller chunks/repos.

**Comment by tmackowski** [comment] 2023-01-10 09:26
I narrowed it down to a single class. During the pull while refreshing the status there was following message displayed:
'Pull aborted: A data record is to be inserted even though a data record with the same primary key or same unique secondary key exists.'
It is replaced by 
'Pull aborted: Repository pull aborted - Job canceled after system exception ERROR_MESSAGE'

**Comment by mbtools** [comment] 2023-01-10 11:29
Can you attach the xml file of the class?

**Comment by tmackowski** [comment] 2023-01-10 12:50
[#int4#iftt_cl_testcase_pi.clas.xml.zip](https://github.com/abapGit/abapGit/files/10382866/int4.iftt_cl_testcase_pi.clas.xml.zip)

**Comment by mbtools** [comment] 2023-01-10 16:49
I don't see anything wrong with the xml. Since it's related to one class only, there's probably some inconsistent metadata in the system already. If you must know, a SQL trace should help to identify the table. Otherwise, deleting the class and then pulling it again will likely avoid the issue.

**Comment by mbtools** [comment] 2023-03-14 10:00
No action

**Closed by mbtools** 2023-03-14 10:00 UTC
Labels: question
